### ISSUE TITLE
Don't need WebID, no ACL?

### ISSUE THREAD

**Issue by linonetwo** [Otto-AA/solid-local-pod#1]
Does it mean anyone can touch localfile, without any permission check?

I think this is good for my usecase though.

**Comment by Otto-AA** [comment]
If you don't build authentication logic into the fetch function it is open to everyone who has access to localhost. You could also require a password being set in the header for every request, for instance checking [here](https://github.com/Otto-AA/solid-local-pod/blob/master/src/solidFileFetch.js#L31) if `options.headers.password` is identical to `"1234"`, else responding with 401/403.
