### ISSUE TITLE
Does this support PATCH using SPARQL?

### ISSUE THREAD

**Issue by linonetwo** [Otto-AA/solid-local-pod#2]
So we can treat a .ttl file as a database to store metadata of files in a folder.

**Comment by Otto-AA** [comment]
>  Does this support PATCH using SPARQL?

The fetch I've written doesn't support patch requests and SPARQL. I also don't think that solid-rest supports it, so I guess it won't be that easy to get SPARQL requests working on this.

> So we can treat a .ttl file as a database to store metadata of files in a folder.

You can still GET a turtle file, make SPARQL queries in your app and then store the result via PUT/POST.

**Comment by linonetwo** [comment]
I guess GET it and change it in app is OK, since it is local, even GETting large file will be fast, thank you!
